[package]
name = "juniper_subscriptions"
version = "0.14.2"
authors = ["nWacky <gosha.evtushenko@gmail.com>"]
description = "Juniper SubscriptionCoordinator and SubscriptionConnection implementations"
license = "BSD-2-Clause"
documentation = "https://docs.rs/juniper_subscriptions"
repository = "https://github.com/graphql-rust/juniper"
edition = "2018"


[dependencies]
juniper = { version = "0.14.2", path = "../juniper", default-features = false }
futures = { version = "=0.3.1", features = ["compat"] }

#[dev-dependencies]
#juniper = { version = "0.14.2", path = "../juniper", features = ["expose-test-schema", "serde_json"] }
#env_logger = "0.5.11"
#log = "0.4.3"

